name: context-variable
on: [push, workflow_dispatch]

jobs:
  jobs_context_variables:
    runs-on: ubuntu-latest
    steps: 
    - name: To use context context variable
      env:
        CONTEXT_VARIABLE: ${{ toJson(github) }}
      run: | 
        echo "nariz de arya"
        echo "*******************"
        echo "*******************"
        echo "*******************"
        echo "${CONTEXT_VARIABLE}"
        echo "*******************"
        echo "*******************"
        echo "*******************"
        echo "Prueba asignar directamente valor variable" 
        echo "TRUE_STATEMENT=Possums are terrible." >> $GITHUB_OUTPUT
