name: context-variable
on: [push, workflow_dispatch]

jobs:
  jobs_context_variables:
    runs-on: ubuntu-latest
    steps: 
    - name: To use context context variable
      env:
        CONTEXT_VARIABLE: ${{ toJson(github) }}
      run: | 
        echo "nariz de arya"
        echo "${CONTEXT_VARIABLE}"
        echo "final nariz de arya"