name: Values Job defaults

on:
  push:
    branches:
 
      - main
defaults:
  run:
    shell: bash
    working-directory: src
jobs:
  first_job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Create Source Directory
        run: mkdir src
        working-directory: .
      - name: Use Python
        run: import os; print("I'm running python! Hissssss! " + os.getcwd())
        shell: python
      - name: Use Bash
        run: echo "I'm running hum-drum bash in $(pwd). Booo."
      - name: Use Bash Also
        run: echo "I'm running bash also, but elsewhere in $(pwd). Booo."
        working-directory: ..
  second_job:
    name: second job
    runs-on: ubuntu-latest
    steps:
      - name: Create source directory
        run: mkdir src
        working-directory: .
      - name: Use Bash
        run: echo "I'm running hum-drum bash in $(pwd). Booo."