name: workflow trigger

on:
  issues:
    types: [opened]

jobs:
  issue_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue information
        env:
          EVENT_NAME: "${{ github.event_name }}"
          EVENT_ACTION: "${{ github.event.action }}"
        run: echo "este es el event_name, '${EVENT_NAME}' "
        
      
    