name: Use actions

on:
  push:
    branches:
      - main

jobs:
  actions:
    name: Run actions
    runs-on: ubuntu-latest
    steps: 
      - name: List directory contents
        run: ls -ltra
      - name: Checkout repository  
        uses: actions/checkout@v3
        with:
          clean: true
      - name: 22 List directory contests again 22
        run: ls -ltra
      - name: Use GitHub Script Action
        uses: actions/github-script@v6
        with:
          script: |
            const create  = await github.rest.issues.create({ 
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Learning To Use Script-Actions!",
              body: "Hey, we used script actions! Here's the commit SHA that triggered this: ${{github.sha}}"
            })
            return create.data.number